package com.konfigthis.client;

import com.konfigthis.client.api.AccessApi;
import com.konfigthis.client.api.ActionApi;
import com.konfigthis.client.api.AiApi;
import com.konfigthis.client.api.AppApi;
import com.konfigthis.client.api.AppConfigApi;
import com.konfigthis.client.api.ApprovalApi;
import com.konfigthis.client.api.ApprovalRequestApi;
import com.konfigthis.client.api.AssessmentApi;
import com.konfigthis.client.api.BandApi;
import com.konfigthis.client.api.BillingApi;
import com.konfigthis.client.api.BudgetPoolApi;
import com.konfigthis.client.api.CalendarApi;
import com.konfigthis.client.api.CategoryApi;
import com.konfigthis.client.api.CategorySortApi;
import com.konfigthis.client.api.ChangeApi;
import com.konfigthis.client.api.CommentApi;
import com.konfigthis.client.api.CompReviewApi;
import com.konfigthis.client.api.ContentApi;
import com.konfigthis.client.api.CustomerApi;
import com.konfigthis.client.api.DataViewApi;
import com.konfigthis.client.api.EmailTemplateApi;
import com.konfigthis.client.api.EventApi;
import com.konfigthis.client.api.ExchangeRateApi;
import com.konfigthis.client.api.ExportApi;
import com.konfigthis.client.api.ExpressionApi;
import com.konfigthis.client.api.FieldApi;
import com.konfigthis.client.api.FileApi;
import com.konfigthis.client.api.FormApi;
import com.konfigthis.client.api.FormResponseApi;
import com.konfigthis.client.api.GroupApi;
import com.konfigthis.client.api.GuidelineApi;
import com.konfigthis.client.api.ImportApi;
import com.konfigthis.client.api.JobApi;
import com.konfigthis.client.api.JobLevelApi;
import com.konfigthis.client.api.LegalDocApi;
import com.konfigthis.client.api.MediaApi;
import com.konfigthis.client.api.MessageApi;
import com.konfigthis.client.api.MetricApi;
import com.konfigthis.client.api.MultiplierApi;
import com.konfigthis.client.api.NotificationApi;
import com.konfigthis.client.api.OauthApi;
import com.konfigthis.client.api.OnboardApi;
import com.konfigthis.client.api.OrgApi;
import com.konfigthis.client.api.OrgConfigApi;
import com.konfigthis.client.api.PersonApi;
import com.konfigthis.client.api.PolicyApi;
import com.konfigthis.client.api.PositionApi;
import com.konfigthis.client.api.PreloadApi;
import com.konfigthis.client.api.ProcessApi;
import com.konfigthis.client.api.ProductApi;
import com.konfigthis.client.api.ProfileTabApi;
import com.konfigthis.client.api.QueryApi;
import com.konfigthis.client.api.QuestionApi;
import com.konfigthis.client.api.ReportApi;
import com.konfigthis.client.api.ReportChartApi;
import com.konfigthis.client.api.RoleApi;
import com.konfigthis.client.api.SamlApi;
import com.konfigthis.client.api.ScenarioApi;
import com.konfigthis.client.api.SearchApi;
import com.konfigthis.client.api.StatusApi;
import com.konfigthis.client.api.StockApi;
import com.konfigthis.client.api.StripeApi;
import com.konfigthis.client.api.TableApi;
import com.konfigthis.client.api.TaskApi;
import com.konfigthis.client.api.TaskConfigApi;
import com.konfigthis.client.api.TemplateApi;
import com.konfigthis.client.api.TimeoffApi;
import com.konfigthis.client.api.UsageApi;
import com.konfigthis.client.api.UserApi;
import com.konfigthis.client.api.WebauthnApi;

public class ChartHop {
    private ApiClient apiClient;
    public final AccessApi access;
    public final ActionApi action;
    public final AiApi ai;
    public final AppApi app;
    public final AppConfigApi appConfig;
    public final ApprovalApi approval;
    public final ApprovalRequestApi approvalRequest;
    public final AssessmentApi assessment;
    public final BandApi band;
    public final BillingApi billing;
    public final BudgetPoolApi budgetPool;
    public final CalendarApi calendar;
    public final CategoryApi category;
    public final CategorySortApi categorySort;
    public final ChangeApi change;
    public final CommentApi comment;
    public final CompReviewApi compReview;
    public final ContentApi content;
    public final CustomerApi customer;
    public final DataViewApi dataView;
    public final EmailTemplateApi emailTemplate;
    public final EventApi event;
    public final ExchangeRateApi exchangeRate;
    public final ExportApi export;
    public final ExpressionApi expression;
    public final FieldApi field;
    public final FileApi file;
    public final FormApi form;
    public final FormResponseApi formResponse;
    public final GroupApi group;
    public final GuidelineApi guideline;
    public final ImportApi import;
    public final JobApi job;
    public final JobLevelApi jobLevel;
    public final LegalDocApi legalDoc;
    public final MediaApi media;
    public final MessageApi message;
    public final MetricApi metric;
    public final MultiplierApi multiplier;
    public final NotificationApi notification;
    public final OauthApi oauth;
    public final OnboardApi onboard;
    public final OrgApi org;
    public final OrgConfigApi orgConfig;
    public final PersonApi person;
    public final PolicyApi policy;
    public final PositionApi position;
    public final PreloadApi preload;
    public final ProcessApi process;
    public final ProductApi product;
    public final ProfileTabApi profileTab;
    public final QueryApi query;
    public final QuestionApi question;
    public final ReportApi report;
    public final ReportChartApi reportChart;
    public final RoleApi role;
    public final SamlApi saml;
    public final ScenarioApi scenario;
    public final SearchApi search;
    public final StatusApi status;
    public final StockApi stock;
    public final StripeApi stripe;
    public final TableApi table;
    public final TaskApi task;
    public final TaskConfigApi taskConfig;
    public final TemplateApi template;
    public final TimeoffApi timeoff;
    public final UsageApi usage;
    public final UserApi user;
    public final WebauthnApi webauthn;

    public ChartHop() {
        this(null);
    }

    public ChartHop(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.access = new AccessApi(this.apiClient);
        this.action = new ActionApi(this.apiClient);
        this.ai = new AiApi(this.apiClient);
        this.app = new AppApi(this.apiClient);
        this.appConfig = new AppConfigApi(this.apiClient);
        this.approval = new ApprovalApi(this.apiClient);
        this.approvalRequest = new ApprovalRequestApi(this.apiClient);
        this.assessment = new AssessmentApi(this.apiClient);
        this.band = new BandApi(this.apiClient);
        this.billing = new BillingApi(this.apiClient);
        this.budgetPool = new BudgetPoolApi(this.apiClient);
        this.calendar = new CalendarApi(this.apiClient);
        this.category = new CategoryApi(this.apiClient);
        this.categorySort = new CategorySortApi(this.apiClient);
        this.change = new ChangeApi(this.apiClient);
        this.comment = new CommentApi(this.apiClient);
        this.compReview = new CompReviewApi(this.apiClient);
        this.content = new ContentApi(this.apiClient);
        this.customer = new CustomerApi(this.apiClient);
        this.dataView = new DataViewApi(this.apiClient);
        this.emailTemplate = new EmailTemplateApi(this.apiClient);
        this.event = new EventApi(this.apiClient);
        this.exchangeRate = new ExchangeRateApi(this.apiClient);
        this.export = new ExportApi(this.apiClient);
        this.expression = new ExpressionApi(this.apiClient);
        this.field = new FieldApi(this.apiClient);
        this.file = new FileApi(this.apiClient);
        this.form = new FormApi(this.apiClient);
        this.formResponse = new FormResponseApi(this.apiClient);
        this.group = new GroupApi(this.apiClient);
        this.guideline = new GuidelineApi(this.apiClient);
        this.import = new ImportApi(this.apiClient);
        this.job = new JobApi(this.apiClient);
        this.jobLevel = new JobLevelApi(this.apiClient);
        this.legalDoc = new LegalDocApi(this.apiClient);
        this.media = new MediaApi(this.apiClient);
        this.message = new MessageApi(this.apiClient);
        this.metric = new MetricApi(this.apiClient);
        this.multiplier = new MultiplierApi(this.apiClient);
        this.notification = new NotificationApi(this.apiClient);
        this.oauth = new OauthApi(this.apiClient);
        this.onboard = new OnboardApi(this.apiClient);
        this.org = new OrgApi(this.apiClient);
        this.orgConfig = new OrgConfigApi(this.apiClient);
        this.person = new PersonApi(this.apiClient);
        this.policy = new PolicyApi(this.apiClient);
        this.position = new PositionApi(this.apiClient);
        this.preload = new PreloadApi(this.apiClient);
        this.process = new ProcessApi(this.apiClient);
        this.product = new ProductApi(this.apiClient);
        this.profileTab = new ProfileTabApi(this.apiClient);
        this.query = new QueryApi(this.apiClient);
        this.question = new QuestionApi(this.apiClient);
        this.report = new ReportApi(this.apiClient);
        this.reportChart = new ReportChartApi(this.apiClient);
        this.role = new RoleApi(this.apiClient);
        this.saml = new SamlApi(this.apiClient);
        this.scenario = new ScenarioApi(this.apiClient);
        this.search = new SearchApi(this.apiClient);
        this.status = new StatusApi(this.apiClient);
        this.stock = new StockApi(this.apiClient);
        this.stripe = new StripeApi(this.apiClient);
        this.table = new TableApi(this.apiClient);
        this.task = new TaskApi(this.apiClient);
        this.taskConfig = new TaskConfigApi(this.apiClient);
        this.template = new TemplateApi(this.apiClient);
        this.timeoff = new TimeoffApi(this.apiClient);
        this.usage = new UsageApi(this.apiClient);
        this.user = new UserApi(this.apiClient);
        this.webauthn = new WebauthnApi(this.apiClient);
    }

}
