/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApprovalGroupApprover;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApprovalGroup
 */
public class ApprovalGroupTest {
    private final ApprovalGroup model = new ApprovalGroup();

    /**
     * Model tests for ApprovalGroup
     */
    @Test
    public void testApprovalGroup() {
        // TODO: test ApprovalGroup
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'approvers'
     */
    @Test
    public void approversTest() {
        // TODO: test approvers
    }

    /**
     * Test the property 'expandExpression'
     */
    @Test
    public void expandExpressionTest() {
        // TODO: test expandExpression
    }

}
