/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobUpdate;
import com.konfigthis.client.model.PartialJob;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateChange
 */
public class CreateChangeTest {
    private final CreateChange model = new CreateChange();

    /**
     * Model tests for CreateChange
     */
    @Test
    public void testCreateChange() {
        // TODO: test CreateChange
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'scenarioId'
     */
    @Test
    public void scenarioIdTest() {
        // TODO: test scenarioId
    }

    /**
     * Test the property 'personId'
     */
    @Test
    public void personIdTest() {
        // TODO: test personId
    }

    /**
     * Test the property 'otherJobId'
     */
    @Test
    public void otherJobIdTest() {
        // TODO: test otherJobId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'announceDate'
     */
    @Test
    public void announceDateTest() {
        // TODO: test announceDate
    }

    /**
     * Test the property 'departType'
     */
    @Test
    public void departTypeTest() {
        // TODO: test departType
    }

    /**
     * Test the property 'departRegret'
     */
    @Test
    public void departRegretTest() {
        // TODO: test departRegret
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'promotionType'
     */
    @Test
    public void promotionTypeTest() {
        // TODO: test promotionType
    }

    /**
     * Test the property 'job'
     */
    @Test
    public void jobTest() {
        // TODO: test job
    }

    /**
     * Test the property 'update'
     */
    @Test
    public void updateTest() {
        // TODO: test update
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

}
