/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContentBlock;
import com.konfigthis.client.model.ShareAccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateContent
 */
public class CreateContentTest {
    private final CreateContent model = new CreateContent();

    /**
     * Model tests for CreateContent
     */
    @Test
    public void testCreateContent() {
        // TODO: test CreateContent
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'parentContentId'
     */
    @Test
    public void parentContentIdTest() {
        // TODO: test parentContentId
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'blocks'
     */
    @Test
    public void blocksTest() {
        // TODO: test blocks
    }

    /**
     * Test the property 'imagePath'
     */
    @Test
    public void imagePathTest() {
        // TODO: test imagePath
    }

    /**
     * Test the property 'emoji'
     */
    @Test
    public void emojiTest() {
        // TODO: test emoji
    }

    /**
     * Test the property 'coverImagePath'
     */
    @Test
    public void coverImagePathTest() {
        // TODO: test coverImagePath
    }

    /**
     * Test the property 'sensitive'
     */
    @Test
    public void sensitiveTest() {
        // TODO: test sensitive
    }

    /**
     * Test the property 'shareAccess'
     */
    @Test
    public void shareAccessTest() {
        // TODO: test shareAccess
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
