/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FormBlock;
import com.konfigthis.client.model.FormField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Form
 */
public class FormTest {
    private final Form model = new Form();

    /**
     * Model tests for Form
     */
    @Test
    public void testForm() {
        // TODO: test Form
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'blocks'
     */
    @Test
    public void blocksTest() {
        // TODO: test blocks
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'targetType'
     */
    @Test
    public void targetTypeTest() {
        // TODO: test targetType
    }

    /**
     * Test the property 'targetFilter'
     */
    @Test
    public void targetFilterTest() {
        // TODO: test targetFilter
    }

    /**
     * Test the property 'submitFilter'
     */
    @Test
    public void submitFilterTest() {
        // TODO: test submitFilter
    }

    /**
     * Test the property 'responseReadFilter'
     */
    @Test
    public void responseReadFilterTest() {
        // TODO: test responseReadFilter
    }

    /**
     * Test the property 'useFieldAccess'
     */
    @Test
    public void useFieldAccessTest() {
        // TODO: test useFieldAccess
    }

    /**
     * Test the property 'approval'
     */
    @Test
    public void approvalTest() {
        // TODO: test approval
    }

    /**
     * Test the property 'authorSensitive'
     */
    @Test
    public void authorSensitiveTest() {
        // TODO: test authorSensitive
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'createId'
     */
    @Test
    public void createIdTest() {
        // TODO: test createId
    }

    /**
     * Test the property 'createAt'
     */
    @Test
    public void createAtTest() {
        // TODO: test createAt
    }

    /**
     * Test the property 'updateId'
     */
    @Test
    public void updateIdTest() {
        // TODO: test updateId
    }

    /**
     * Test the property 'updateAt'
     */
    @Test
    public void updateAtTest() {
        // TODO: test updateAt
    }

    /**
     * Test the property 'deleteId'
     */
    @Test
    public void deleteIdTest() {
        // TODO: test deleteId
    }

    /**
     * Test the property 'deleteAt'
     */
    @Test
    public void deleteAtTest() {
        // TODO: test deleteAt
    }

}
