/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportGroupByKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportGroupByDimension
 */
public class ReportGroupByDimensionTest {
    private final ReportGroupByDimension model = new ReportGroupByDimension();

    /**
     * Model tests for ReportGroupByDimension
     */
    @Test
    public void testReportGroupByDimension() {
        // TODO: test ReportGroupByDimension
    }

    /**
     * Test the property 'keys'
     */
    @Test
    public void keysTest() {
        // TODO: test keys
    }

}
