/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Policy;
import com.konfigthis.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Role
 */
public class RoleTest {
    private final Role model = new Role();

    /**
     * Model tests for Role
     */
    @Test
    public void testRole() {
        // TODO: test Role
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'policyIds'
     */
    @Test
    public void policyIdsTest() {
        // TODO: test policyIds
    }

    /**
     * Test the property 'policies'
     */
    @Test
    public void policiesTest() {
        // TODO: test policies
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

    /**
     * Test the property 'createId'
     */
    @Test
    public void createIdTest() {
        // TODO: test createId
    }

    /**
     * Test the property 'createAt'
     */
    @Test
    public void createAtTest() {
        // TODO: test createAt
    }

    /**
     * Test the property 'updateId'
     */
    @Test
    public void updateIdTest() {
        // TODO: test updateId
    }

    /**
     * Test the property 'updateAt'
     */
    @Test
    public void updateAtTest() {
        // TODO: test updateAt
    }

    /**
     * Test the property 'deleteId'
     */
    @Test
    public void deleteIdTest() {
        // TODO: test deleteId
    }

    /**
     * Test the property 'deleteAt'
     */
    @Test
    public void deleteAtTest() {
        // TODO: test deleteAt
    }

}
