/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestEmailRequest
 */
public class TestEmailRequestTest {
    private final TestEmailRequest model = new TestEmailRequest();

    /**
     * Model tests for TestEmailRequest
     */
    @Test
    public void testTestEmailRequest() {
        // TODO: test TestEmailRequest
    }

    /**
     * Test the property 'welcomeEmailSubject'
     */
    @Test
    public void welcomeEmailSubjectTest() {
        // TODO: test welcomeEmailSubject
    }

    /**
     * Test the property 'welcomeEmailButtonLabel'
     */
    @Test
    public void welcomeEmailButtonLabelTest() {
        // TODO: test welcomeEmailButtonLabel
    }

    /**
     * Test the property 'welcomeEmailBody'
     */
    @Test
    public void welcomeEmailBodyTest() {
        // TODO: test welcomeEmailBody
    }

}
