/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApprovalGroup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateApprovalChainStage
 */
public class UpdateApprovalChainStageTest {
    private final UpdateApprovalChainStage model = new UpdateApprovalChainStage();

    /**
     * Model tests for UpdateApprovalChainStage
     */
    @Test
    public void testUpdateApprovalChainStage() {
        // TODO: test UpdateApprovalChainStage
    }

    /**
     * Test the property 'inclusionExpression'
     */
    @Test
    public void inclusionExpressionTest() {
        // TODO: test inclusionExpression
    }

    /**
     * Test the property 'inclusionBehavior'
     */
    @Test
    public void inclusionBehaviorTest() {
        // TODO: test inclusionBehavior
    }

    /**
     * Test the property 'expandExpression'
     */
    @Test
    public void expandExpressionTest() {
        // TODO: test expandExpression
    }

    /**
     * Test the property 'rejectBehavior'
     */
    @Test
    public void rejectBehaviorTest() {
        // TODO: test rejectBehavior
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'approvalCommentRequired'
     */
    @Test
    public void approvalCommentRequiredTest() {
        // TODO: test approvalCommentRequired
    }

    /**
     * Test the property 'rejectionCommentRequired'
     */
    @Test
    public void rejectionCommentRequiredTest() {
        // TODO: test rejectionCommentRequired
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

}
