/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MoneyRange;
import com.konfigthis.client.model.ValueRange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BasisCondition
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BasisCondition {
  public static final String SERIALIZED_NAME_CONDITION_EXPR = "conditionExpr";
  @SerializedName(SERIALIZED_NAME_CONDITION_EXPR)
  private String conditionExpr;

  public static final String SERIALIZED_NAME_AMOUNT_RANGE = "amountRange";
  @SerializedName(SERIALIZED_NAME_AMOUNT_RANGE)
  private MoneyRange amountRange;

  public static final String SERIALIZED_NAME_VALUE_RANGE = "valueRange";
  @SerializedName(SERIALIZED_NAME_VALUE_RANGE)
  private ValueRange valueRange;

  public BasisCondition() {
  }

  public BasisCondition conditionExpr(String conditionExpr) {
    
    
    
    
    this.conditionExpr = conditionExpr;
    return this;
  }

   /**
   * Get conditionExpr
   * @return conditionExpr
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getConditionExpr() {
    return conditionExpr;
  }


  public void setConditionExpr(String conditionExpr) {
    
    
    
    this.conditionExpr = conditionExpr;
  }


  public BasisCondition amountRange(MoneyRange amountRange) {
    
    
    
    
    this.amountRange = amountRange;
    return this;
  }

   /**
   * Get amountRange
   * @return amountRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MoneyRange getAmountRange() {
    return amountRange;
  }


  public void setAmountRange(MoneyRange amountRange) {
    
    
    
    this.amountRange = amountRange;
  }


  public BasisCondition valueRange(ValueRange valueRange) {
    
    
    
    
    this.valueRange = valueRange;
    return this;
  }

   /**
   * Get valueRange
   * @return valueRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ValueRange getValueRange() {
    return valueRange;
  }


  public void setValueRange(ValueRange valueRange) {
    
    
    
    this.valueRange = valueRange;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BasisCondition instance itself
   */
  public BasisCondition putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasisCondition basisCondition = (BasisCondition) o;
    return Objects.equals(this.conditionExpr, basisCondition.conditionExpr) &&
        Objects.equals(this.amountRange, basisCondition.amountRange) &&
        Objects.equals(this.valueRange, basisCondition.valueRange)&&
        Objects.equals(this.additionalProperties, basisCondition.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditionExpr, amountRange, valueRange, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasisCondition {\n");
    sb.append("    conditionExpr: ").append(toIndentedString(conditionExpr)).append("\n");
    sb.append("    amountRange: ").append(toIndentedString(amountRange)).append("\n");
    sb.append("    valueRange: ").append(toIndentedString(valueRange)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("conditionExpr");
    openapiFields.add("amountRange");
    openapiFields.add("valueRange");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("conditionExpr");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BasisCondition
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BasisCondition.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BasisCondition is not found in the empty JSON string", BasisCondition.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BasisCondition.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("conditionExpr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `conditionExpr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conditionExpr").toString()));
      }
      // validate the optional field `amountRange`
      if (jsonObj.get("amountRange") != null && !jsonObj.get("amountRange").isJsonNull()) {
        MoneyRange.validateJsonObject(jsonObj.getAsJsonObject("amountRange"));
      }
      // validate the optional field `valueRange`
      if (jsonObj.get("valueRange") != null && !jsonObj.get("valueRange").isJsonNull()) {
        ValueRange.validateJsonObject(jsonObj.getAsJsonObject("valueRange"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BasisCondition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BasisCondition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BasisCondition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BasisCondition.class));

       return (TypeAdapter<T>) new TypeAdapter<BasisCondition>() {
           @Override
           public void write(JsonWriter out, BasisCondition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BasisCondition read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BasisCondition instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BasisCondition given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BasisCondition
  * @throws IOException if the JSON string is invalid with respect to BasisCondition
  */
  public static BasisCondition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BasisCondition.class);
  }

 /**
  * Convert an instance of BasisCondition to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

