/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GraphCount
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GraphCount {
  public static final String SERIALIZED_NAME_UNDER = "under";
  @SerializedName(SERIALIZED_NAME_UNDER)
  private Integer under;

  public static final String SERIALIZED_NAME_SIBLING = "sibling";
  @SerializedName(SERIALIZED_NAME_SIBLING)
  private Integer sibling;

  public static final String SERIALIZED_NAME_UNDER_UNFILLED = "underUnfilled";
  @SerializedName(SERIALIZED_NAME_UNDER_UNFILLED)
  private Integer underUnfilled;

  public static final String SERIALIZED_NAME_SIBLING_UNFILLED = "siblingUnfilled";
  @SerializedName(SERIALIZED_NAME_SIBLING_UNFILLED)
  private Integer siblingUnfilled;

  public GraphCount() {
  }

  public GraphCount under(Integer under) {
    
    
    
    
    this.under = under;
    return this;
  }

   /**
   * Get under
   * @return under
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getUnder() {
    return under;
  }


  public void setUnder(Integer under) {
    
    
    
    this.under = under;
  }


  public GraphCount sibling(Integer sibling) {
    
    
    
    
    this.sibling = sibling;
    return this;
  }

   /**
   * Get sibling
   * @return sibling
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSibling() {
    return sibling;
  }


  public void setSibling(Integer sibling) {
    
    
    
    this.sibling = sibling;
  }


  public GraphCount underUnfilled(Integer underUnfilled) {
    
    
    
    
    this.underUnfilled = underUnfilled;
    return this;
  }

   /**
   * Get underUnfilled
   * @return underUnfilled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getUnderUnfilled() {
    return underUnfilled;
  }


  public void setUnderUnfilled(Integer underUnfilled) {
    
    
    
    this.underUnfilled = underUnfilled;
  }


  public GraphCount siblingUnfilled(Integer siblingUnfilled) {
    
    
    
    
    this.siblingUnfilled = siblingUnfilled;
    return this;
  }

   /**
   * Get siblingUnfilled
   * @return siblingUnfilled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSiblingUnfilled() {
    return siblingUnfilled;
  }


  public void setSiblingUnfilled(Integer siblingUnfilled) {
    
    
    
    this.siblingUnfilled = siblingUnfilled;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GraphCount instance itself
   */
  public GraphCount putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GraphCount graphCount = (GraphCount) o;
    return Objects.equals(this.under, graphCount.under) &&
        Objects.equals(this.sibling, graphCount.sibling) &&
        Objects.equals(this.underUnfilled, graphCount.underUnfilled) &&
        Objects.equals(this.siblingUnfilled, graphCount.siblingUnfilled)&&
        Objects.equals(this.additionalProperties, graphCount.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(under, sibling, underUnfilled, siblingUnfilled, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GraphCount {\n");
    sb.append("    under: ").append(toIndentedString(under)).append("\n");
    sb.append("    sibling: ").append(toIndentedString(sibling)).append("\n");
    sb.append("    underUnfilled: ").append(toIndentedString(underUnfilled)).append("\n");
    sb.append("    siblingUnfilled: ").append(toIndentedString(siblingUnfilled)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("under");
    openapiFields.add("sibling");
    openapiFields.add("underUnfilled");
    openapiFields.add("siblingUnfilled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("under");
    openapiRequiredFields.add("sibling");
    openapiRequiredFields.add("underUnfilled");
    openapiRequiredFields.add("siblingUnfilled");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GraphCount
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GraphCount.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GraphCount is not found in the empty JSON string", GraphCount.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GraphCount.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GraphCount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GraphCount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GraphCount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GraphCount.class));

       return (TypeAdapter<T>) new TypeAdapter<GraphCount>() {
           @Override
           public void write(JsonWriter out, GraphCount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GraphCount read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GraphCount instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GraphCount given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GraphCount
  * @throws IOException if the JSON string is invalid with respect to GraphCount
  */
  public static GraphCount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GraphCount.class);
  }

 /**
  * Convert an instance of GraphCount to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

