/*
 * ChartHop API
 * REST API for ChartHop
 *
 * The version of the OpenAPI document: V1.0.0
 * Contact: support@charthop.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ScenarioCalculation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PoolCalculation
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PoolCalculation {
  public static final String SERIALIZED_NAME_BUDGET_POOL_ID = "budgetPoolId";
  @SerializedName(SERIALIZED_NAME_BUDGET_POOL_ID)
  private String budgetPoolId;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_ALLOCATED = "allocated";
  @SerializedName(SERIALIZED_NAME_ALLOCATED)
  private Object allocated;

  public static final String SERIALIZED_NAME_USED = "used";
  @SerializedName(SERIALIZED_NAME_USED)
  private Object used;

  public static final String SERIALIZED_NAME_SCENARIOS = "scenarios";
  @SerializedName(SERIALIZED_NAME_SCENARIOS)
  private List<ScenarioCalculation> scenarios = new ArrayList<>();

  public PoolCalculation() {
  }

  public PoolCalculation budgetPoolId(String budgetPoolId) {
    
    
    
    
    this.budgetPoolId = budgetPoolId;
    return this;
  }

   /**
   * budget pool id
   * @return budgetPoolId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "588f7ee98f138b19220041a7", required = true, value = "budget pool id")

  public String getBudgetPoolId() {
    return budgetPoolId;
  }


  public void setBudgetPoolId(String budgetPoolId) {
    
    
    
    this.budgetPoolId = budgetPoolId;
  }


  public PoolCalculation label(String label) {
    
    
    
    
    this.label = label;
    return this;
  }

   /**
   * budget pool label
   * @return label
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Merit", required = true, value = "budget pool label")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    
    
    
    this.label = label;
  }


  public PoolCalculation allocated(Object allocated) {
    
    
    
    
    this.allocated = allocated;
    return this;
  }

   /**
   * budget pool total amount
   * @return allocated
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "500", required = true, value = "budget pool total amount")

  public Object getAllocated() {
    return allocated;
  }


  public void setAllocated(Object allocated) {
    
    
    
    this.allocated = allocated;
  }


  public PoolCalculation used(Object used) {
    
    
    
    
    this.used = used;
    return this;
  }

   /**
   * the amount of the budget pool that has been used
   * @return used
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500", value = "the amount of the budget pool that has been used")

  public Object getUsed() {
    return used;
  }


  public void setUsed(Object used) {
    
    
    
    this.used = used;
  }


  public PoolCalculation scenarios(List<ScenarioCalculation> scenarios) {
    
    
    
    
    this.scenarios = scenarios;
    return this;
  }

  public PoolCalculation addScenariosItem(ScenarioCalculation scenariosItem) {
    this.scenarios.add(scenariosItem);
    return this;
  }

   /**
   * a list of reviewer/scenario specific calculations that create the total
   * @return scenarios
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "a list of reviewer/scenario specific calculations that create the total")

  public List<ScenarioCalculation> getScenarios() {
    return scenarios;
  }


  public void setScenarios(List<ScenarioCalculation> scenarios) {
    
    
    
    this.scenarios = scenarios;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PoolCalculation instance itself
   */
  public PoolCalculation putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoolCalculation poolCalculation = (PoolCalculation) o;
    return Objects.equals(this.budgetPoolId, poolCalculation.budgetPoolId) &&
        Objects.equals(this.label, poolCalculation.label) &&
        Objects.equals(this.allocated, poolCalculation.allocated) &&
        Objects.equals(this.used, poolCalculation.used) &&
        Objects.equals(this.scenarios, poolCalculation.scenarios)&&
        Objects.equals(this.additionalProperties, poolCalculation.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budgetPoolId, label, allocated, used, scenarios, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoolCalculation {\n");
    sb.append("    budgetPoolId: ").append(toIndentedString(budgetPoolId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    allocated: ").append(toIndentedString(allocated)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    scenarios: ").append(toIndentedString(scenarios)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("budgetPoolId");
    openapiFields.add("label");
    openapiFields.add("allocated");
    openapiFields.add("used");
    openapiFields.add("scenarios");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("budgetPoolId");
    openapiRequiredFields.add("label");
    openapiRequiredFields.add("allocated");
    openapiRequiredFields.add("scenarios");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PoolCalculation
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PoolCalculation.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PoolCalculation is not found in the empty JSON string", PoolCalculation.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PoolCalculation.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("budgetPoolId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `budgetPoolId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("budgetPoolId").toString()));
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("scenarios").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `scenarios` to be an array in the JSON string but got `%s`", jsonObj.get("scenarios").toString()));
      }

      JsonArray jsonArrayscenarios = jsonObj.getAsJsonArray("scenarios");
      // validate the required field `scenarios` (array)
      for (int i = 0; i < jsonArrayscenarios.size(); i++) {
        ScenarioCalculation.validateJsonObject(jsonArrayscenarios.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PoolCalculation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PoolCalculation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PoolCalculation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PoolCalculation.class));

       return (TypeAdapter<T>) new TypeAdapter<PoolCalculation>() {
           @Override
           public void write(JsonWriter out, PoolCalculation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PoolCalculation read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PoolCalculation instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PoolCalculation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PoolCalculation
  * @throws IOException if the JSON string is invalid with respect to PoolCalculation
  */
  public static PoolCalculation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PoolCalculation.class);
  }

 /**
  * Convert an instance of PoolCalculation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

